// Generated by tools/generate-provider-configuration.mjs from config/providers/*.json (ADR 0073 §2). Do not edit:
// edit the provider documents and run `node tools/generate-provider-configuration.mjs`; `check` fails when
// this file is not what the documents generate. Shared by the protocol, the service and the renderer: identifiers and labels only.

/** Every route a provider document declares, bindable or not: the members of `RemoteProviderId` and `RemoteExecutionRoute`. */
export const CONFIGURED_ROUTE_IDS = [
  'alibaba-model-studio',
  'anthropic-claude',
  'baidu-qianfan',
  'deepseek-open-platform',
  'google-gemini',
  'minimax',
  'moonshot-kimi',
  'openai-platform',
  'opencode-go',
  'opencode-go-messages',
  'opencode-go-responses',
  'opencode-zen',
  'opencode-zen-messages',
  'opencode-zen-responses',
  'tencent-hunyuan',
  'xiaomi-mimo',
  'zhipu-glm',
] as const;
export type ConfiguredRouteId = (typeof CONFIGURED_ROUTE_IDS)[number];

/** One credential slot per configured provider (ADR 0073 §4): the members of `CredentialSlotId`, and the Credential Broker's closed set. */
export const CONFIGURED_CREDENTIAL_SLOTS = [
  'alibaba-model-studio',
  'anthropic-claude',
  'baidu-qianfan',
  'deepseek-api-key',
  'google-gemini',
  'minimax',
  'moonshot-kimi',
  'openai-platform',
  'opencode-go',
  'opencode-zen',
  'tencent-hunyuan',
  'xiaomi-mimo',
  'zhipu-glm',
] as const;
export type ConfiguredCredentialSlot = (typeof CONFIGURED_CREDENTIAL_SLOTS)[number];

/** The provider's name beside a model id in a plan, by route. */
export const CONFIGURED_PROVIDER_LABELS: Readonly<Record<ConfiguredRouteId, string>> = {
  'alibaba-model-studio': '阿里云百炼 Qwen',
  'anthropic-claude': 'Claude 官方',
  'baidu-qianfan': '百度文心（千帆）',
  'deepseek-open-platform': 'DeepSeek 开放平台',
  'google-gemini': 'Gemini 官方',
  'minimax': 'MiniMax',
  'moonshot-kimi': '月之暗面 Kimi',
  'openai-platform': 'OpenAI 官方',
  'opencode-go': 'OpenCode Go',
  'opencode-go-messages': 'OpenCode Go',
  'opencode-go-responses': 'OpenCode Go',
  'opencode-zen': 'OpenCode Zen',
  'opencode-zen-messages': 'OpenCode Zen',
  'opencode-zen-responses': 'OpenCode Zen',
  'tencent-hunyuan': '腾讯混元',
  'xiaomi-mimo': '小米 MiMo',
  'zhipu-glm': '智谱 GLM',
};

/** The slots whose document fixes a development Credential Reference; the production connection's slot has none. */
export const CONFIGURED_DEVELOPMENT_SLOTS = [
  'alibaba-model-studio',
  'anthropic-claude',
  'baidu-qianfan',
  'google-gemini',
  'minimax',
  'moonshot-kimi',
  'openai-platform',
  'opencode-go',
  'opencode-zen',
  'tencent-hunyuan',
  'xiaomi-mimo',
  'zhipu-glm',
] as const;
export type ConfiguredDevelopmentSlot = (typeof CONFIGURED_DEVELOPMENT_SLOTS)[number];

/**
 * The fixed development Credential Reference of each such slot (ADR 0067, ADR 0073 §4): the Protected Secret Store entry the
 * enrollment helper writes under on a developer host. A reference names a store entry and is not a secret, and it is a
 * place for a key, not a permission to enrol one: only `opencode-go` enrolment is authorized (ADR 0067; ADR 0073 §5
 * authorizes no credential).
 */
export const CONFIGURED_DEVELOPMENT_CREDENTIAL_REFERENCES: Readonly<Record<ConfiguredDevelopmentSlot, string>> = {
  'alibaba-model-studio': '41bfff73-4c97-44b2-a88c-ef51b208d589',
  'anthropic-claude': 'a7eb2fde-89f4-4f45-9f24-3e8d0719201e',
  'baidu-qianfan': '9d31099e-30cc-4cf0-b9cd-90887462f653',
  'google-gemini': '65691f57-e3e2-49be-8fb0-cfad51dedaf3',
  'minimax': '3250a08e-e2ba-40aa-93b4-04290ac96deb',
  'moonshot-kimi': 'a6a309a9-7cd5-4cd2-ae31-ba421182af35',
  'openai-platform': 'c8c4e0f8-27dd-45ad-8c60-580a5d58b799',
  'opencode-go': 'a7c0de00-5040-4f27-9e13-6b1f2c8d4a55',
  'opencode-zen': 'faecf1c0-7946-4de0-87b7-abd84f0e1883',
  'tencent-hunyuan': 'ed50a5e5-47d7-4477-bac6-6eb0237f3327',
  'xiaomi-mimo': 'e03b8ea8-2a10-4c60-909e-82a5976e2810',
  'zhipu-glm': '1bfa4e14-ce91-4666-bc69-eb72709379f0',
};
